---
# [int] Frames per second (use 30 for a genuine QWOP experience)
fps: 30

# [int] End-game screen duration in seconds
reset_delay: 1

# [string] Path to the file to load the model from
model_file: "data/GAIL_PPO-rzn2ucpg/model.zip"

# [string] Module name of the learner alrogirthm (eg. "stable_baselines3")
model_mod: "stable_baselines3"

# [string] Class name of the learner algorithm (eg. "PPO")
model_cls: "PPO"

# [int] Number times to call `env.step()` per action
# It should be equal to the value of `frames_per_step` used during training,
# while `frames_per_step` here should be set to 1 to make the rendering smooth.
steps_per_step: 4

# Env parameters
# The special "__include__" key allows to load them from another file.
# Keys listed here take precedence over keys loaded with __include__.
# See notes in `env.yml` for more info
env_kwargs:
  __include__: "config/env.yml"
  frames_per_step: 1
  auto_draw: true
  stat_in_browser: true
  game_in_browser: true
  text_in_browser: "AI is playing"

# List of gym wrappers to use for the env
# Each list element must be a dict with "module", "cls" and "kwargs" keys
env_wrappers:
  # VerboseWrapper prints action and some game stats on each step
  - module: "src.env.v1.util.verbose_wrapper"
    cls: "VerboseWrapper"
